Upgrade MooseX::ClassAttribute version prerequisite to work with later versions of Moose
MooseX::ClassAttribute 0.27 fixed a bug that resulted from a change in Moose::Util 2.08, in which _caller_info() returns a hash instead of a hashref.

The error from CPAN Testers:

Odd number of elements in hash assignment at C:/sp5-14-4-32b/perl/vendor/lib/MooseX/ClassAttribute.pm line 37.

#   Failed test 'use Flyweight::Test3;'
#   at t/custom_normalizer.t line 12.
#     Tried to use 'Flyweight::Test3'.
#     Error:  Can't use string ("file") as a HASH ref while "strict refs" in use at C:/sp5-14-4-32b/perl/site/lib/Moose/Meta/Attribute.pm line 106.
# Compilation failed in require at (eval 318) line 2.
# BEGIN failed--compilation aborted at (eval 318) line 2.

Moose::Util 2.0802
MooseX::ClassAttribute 0.26